url: "https://bioinformaticsdotca.github.io/MIC_2022"
title: "CBW Workshop GitHub"
description: "CBW focuses on training researchers to use the latest approaches in computational biology to deal with large dataset."
google_analytics_tracking_id: UA-18554799-8
permalink: /2022_workshops/:year/:month/:title.html
github_username: bioinformatics-ca
baseurl: ''
filesurl: '/files'

markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"

language: "en"

defaults:
  -
    scope:
      path: "" 		
      type: "pages"
    values:
      show_meta: false		
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true
  
