url: "https://bioinformaticsdotca.github.io/MIC_2022"
title: "IMPACTT Workshop 2022"
description: "Integrated Microbiome Platforms for Advancing Causation Testing and Translation."
google_analytics_tracking_id: UA-18554799-8
logo: /MIC_2022/IMPACTT_logo.jpg
github_username: bioinformatics-ca
baseurl: ''

markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"

language: "en"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_meta: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true
